#trigger:
#- master

pool:
  vmImage: ubuntu-latest

workspace:
  clean: all

steps:
- task: SynopsysPolaris@1
  displayName: 'Synopsys Polaris Scan'
  inputs:
    polarisService: 'SIPSE_POLARIS'
    polarisCommand: 'analyze -w -- mvn -B compile -DskipTests'